#!/bin/bash
source /lib/lsb/init-functions
if [ "$(id -u)" != "0" ]; then
	log_begin_msg Installing user prompt
	PS1='[ \e[1;$([ $PREVEXITCODE == 0 ] && echo 32 || ([ $PREVEXITCODE -gt 128 ] && echo 31 || echo 33))m$(printf %3s $PREVEXITCODE)\e[0m ][ \e[1;32m$(printf %8s \u)@\h\e[0m ][ \e[0;32m\d @ \t\e[0m ][ \e[0;34m\w\e[0m ]\n\$ '
	echo "PROMPT_COMMAND='export PREVEXITCODE=\$?'" > ~/.bashprompt
	echo "PS1='$PS1'" >> ~/.bashprompt
	echo 'source ~/.bashprompt' >> ~/.bashrc
	log_success_msg
else
	log_begin_msg Installing root prompt
	PS1='[ \e[1;$([ $PREVEXITCODE == 0 ] && echo 32 || ([ $PREVEXITCODE -gt 128 ] && echo 31 || echo 33))m$(printf %3s $PREVEXITCODE)\e[0m ][ \e[1;31m$(printf %8s \u)@\h\e[0m ][ \e[0;31m\d @ \t\e[0m ][ \e[0;33m\w\e[0m ]\n\$ '
	echo "PROMPT_COMMAND='export PREVEXITCODE=\$?'" > ~/.bashprompt
	echo "PS1='$PS1'" >> ~/.bashprompt
	echo 'source ~/.bashprompt' >> ~/.bashrc
	log_success_msg
fi
log_action_msg Run \'source \~/.bashprompt\' to install your new prompt into your current shell session
