#!/bin/bash
if [[ -z "$1" || -z "$2" ]]; then
	echo ytrip: usage: ytrip \<url\> \<outfile\>
	exit 1
fi
URL=`livestreamer -j $1 best |jq -r .url`
ffmpeg -f mp4 -i $URL -f ogg -vn -acodec libvorbis $2
vorbisgain $2
